### ISSUE TITLE
FEATURE: awx_team_role, awx_organization_role, awx_job_template_role, awx_credential_role

### ISSUE THREAD

**Issue by kladiv** [denouche/terraform-provider-awx#11]
Hello,
- can you add the Data Source `awx_team_role` to add a Team the grant of "Member" of another team?
  This is supported by Ansible AWX APIs (even if not shown in AWX UI) and useful for RBAC management

- can you add the Data Source `awx_organization_role` to add a Team or a User a specific grant to a Job Template (e.g. `Inventory Admin`, `Credentials Admin`, `Project Admin`, `Execute` etc. roles)?
This is supported by Ansible AWX APIs and UI

- can you add the Data Source `awx_job_template_role` to add a Team or a User a specific grant to a Job Template (e.g. `Execute` role)?
This is supported by Ansible AWX APIs and UI

- can you add the Data Source `awx_credential_role` to add a Team or a User a specific grant to a Credential (e.g. `Use` role)?
This is supported by Ansible AWX APIs and UI

Useful ref. of Ansible AWX collection: https://docs.ansible.com/ansible/latest/collections/awx/awx/role_module.html#ansible-collections-awx-awx-role-module

Thank you!
Claudio

**Comment by denouche** [comment]
Hello @kladiv ,
I know the terraform provider is not complete for now but we will add the others resources by opportunity when we will need them.
If you need them feel free to submit a PR and contribute to this provider!
Thank you
