### ISSUE TITLE
Support for Amazon Web Services Credentials

### ISSUE THREAD

**Issue by emoshaya** [denouche/terraform-provider-awx#23]
Could you support a new credential type in the form of Amazon Web Services?
![image](https://user-images.githubusercontent.com/8818542/201163301-dc39b284-e56b-45e8-86e6-6dc27f7ea827.png)

**Comment by denouche** [comment]
Hello @emoshaya,
I know the terraform provider is not complete for now but we will add the others resources by opportunity when we will need them.
If you need them feel free to submit a PR and contribute to this provider!
Thank you
