### ISSUE TITLE
terraform-provider-awx_v0.19.0 plugin crashed!

### ISSUE THREAD

**Issue by bhaski153** [denouche/terraform-provider-awx#32]
we get below issue while connecting to denouche awx provider . any idea ?

terraform-provider-awx_v0.19.0 plugin crashed!

panic: runtime error: index out of range [0] with length 0

goroutine 30 [running]:
github.com/denouche/terraform-provider-awx/awx.dataSourceInventoriesRead({0xd04c78, 0xc0004180c0}, 0x7eb9564dbf18, {0xad66a0, 0xc000162300})
	github.com/denouche/terraform-provider-awx/awx/data_source_inventory.go:87 +0x68b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0003a2a80, {0xd04c78, 0xc0004180c0}, 0xc00054a5a0, {0xad66a0, 0xc000162300})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:358 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0003a2a80, {0xd04c78, 0xc0004180c0}, 0xc0000e3180, {0xad66a0, 0xc000162300})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:569 +0xf7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc00000d578, {0xd04c78, 0xc0004180c0}, 0xc00031ca60)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:1133 +0x3a8
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc00014f080, {0xd04d20, 0xc000409cb0}, 0xc000472870)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:478 +0x37b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0xbcf200, 0xc00014f080}, {0xd04d20, 0xc000409cb0}, 0xc000510de0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00027b340, {0xd12678, 0xc000200780}, 0xc0000b6400, 0xc0003c5380, 0x11da9d0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc00027b340, {0xd12678, 0xc000200780}, 0xc0000b6400, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x294

**Comment by jnahelou** [comment]
Can you verify if the issue has been resolved by the commit fa53eac9aa1ec3be4ceedda15e6b6a2173c9ed18 ?
